language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: linux
      compiler: musl-gcc
      addons:
        apt:
          packages:
            - musl
            - musl-dev
            - musl-tools
    - language: node_js
      node_js: "node"
      sudo: required
      services: ["docker"]
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
        - docker exec -it emscripten make test.js
        - make check-js
    - language: node_js
      node_js: "lts/*"
      sudo: required
      services: ["docker"]
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
        - docker exec -it emscripten make test.js
        - make check-js
script:
  - make
  - make check
